"kirin vs kirin-chess"

[kirin vs kirin-chess.Engine One]
blackWins = 0
whiteWins = 1
blackDraws = 0
whiteDraws = 0

[kirin vs kirin-chess.Engine Two]
blackWins = 0
whiteWins = 0
blackDraws = 0
whiteDraws = 0
